version: '3.8'
services:
  wpa-sec:
    image: wpa-sec-docker-nividia:latest
    stdin_open: true  # equivalent to -i
    tty: true         # equivalent to -t
    runtime: nvidia   # necessary for GPU support with Docker and NVIDIA
    volumes:
      - ~/.docker-data/wpa-sec-docker:/app/data
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all